---
    # repository and branch of the infrastructure code
    git_repo_https: https://github.com/ashwini2206soni/text-to-speech.git
    git_branch: master
    # Terraform variables
    gcp_credentials: ((credentials))
    # for foundational code use 'default'
